apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - https://github.com/insolar/gitops/assured-ledger/aks-15node
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:	
  - name: azurecr	
    files:	
      - .dockerconfigjson=dockerconfigjson	
    type: kubernetes.io/dockerconfigjson
