apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: virtual
spec:
  selector:
    matchLabels:
      app: virtual
  replicas: 20
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - virtual
              topologyKey: kubernetes.io/hostname
      imagePullSecrets:
        - name: azurecr
      containers:
        - name: insolar
          resources:
            limits:
              cpu: "1930m"
              memory: 1Gi
            requests:
              cpu: "1930m"
              memory: 1Gi
