netparams:
- nodescount: 80
  waitinreadystate: 5m
  waitbootstrap: 1h
  waitready: 1h
- nodescount: 100
  waitinreadystate: 10m
  waitbootstrap: 1h
  waitready: 1h

kubeparams:
  env: aks
  kuberootpath: /../scripts/deploy/kube/
  manifestsrelpath: manifests/
  bootstrapconfigrelpath: manifests/configuration/
  leaveinsolaraliveiffailed: true
  prometheus:
    enabled: false
    manifestsrelpath: prometheus/
  logcollector:
    enabled: true
    pathtosave: /tmp/insolar/logs/

metricparams:
  quantiles: ["0.5", "0.8", "0.95", "0.99"]
  webdav:
    timeout: "1m"
