nodes:
- virtual-0.platform-network:19001
- virtual-1.platform-network:19001
- virtual-2.platform-network:19001
- virtual-3.platform-network:19001
- virtual-4.platform-network:19001
- virtual-5.platform-network:19001
- virtual-6.platform-network:19001
- virtual-7.platform-network:19001
- virtual-8.platform-network:19001
- virtual-9.platform-network:19001
- virtual-10.platform-network:19001
- virtual-11.platform-network:19001
- virtual-12.platform-network:19001
- virtual-13.platform-network:19001
- virtual-14.platform-network:19001
- virtual-15.platform-network:19001
- virtual-16.platform-network:19001
- virtual-17.platform-network:19001
- virtual-18.platform-network:19001
- virtual-19.platform-network:19001
interval: 500ms
timeout: 1s
