log:
  level: info
pulsar:
  pulsetime: 10000
  receivingsigntimeout: 1000
  receivingnumbertimeout: 1000
  receivingvectortimeout: 1000
  receivingsignsforchosentimeout: 0
  neighbours: []
  numberdelta: 10
  distributiontransport:
    protocol: TCP
  #    address: 127.0.0.1:58091
  #    fixedpublicaddress: ""
  pulsedistributor:
    bootstraphosts:
      - virtual-0.platform-network:13831
      - virtual-1.platform-network:13831
      - virtual-2.platform-network:13831
      - virtual-3.platform-network:13831
      - virtual-4.platform-network:13831
      - virtual-5.platform-network:13831
      - virtual-6.platform-network:13831
      - virtual-7.platform-network:13831
      - virtual-8.platform-network:13831
      - virtual-9.platform-network:13831
      - virtual-10.platform-network:13831
      - virtual-11.platform-network:13831
      - virtual-12.platform-network:13831
      - virtual-13.platform-network:13831
      - virtual-14.platform-network:13831
      - virtual-15.platform-network:13831
      - virtual-16.platform-network:13831
      - virtual-17.platform-network:13831
      - virtual-18.platform-network:13831
      - virtual-19.platform-network:13831
    pingrequesttimeout: 1000
    randomhostsrequesttimeout: 1000
    pulserequesttimeout: 1000
    randomnodescount: 5
keyspath: "/etc/insolar/keys/pulsar-0.json" # TODO after https://insolar.atlassian.net/browse/PENV-123
tracer:
  jaeger:
    collectorendpoint: ""
    agentendpoint: ""
    probabilityrate: 1
metrics:
  listenaddress: 0.0.0.0:9090
  namespace: placeholder
  zpagesenabled: false
  reportingperiod: 0s
