apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 0-Namespace.yaml
  - 1-bootstrap.yaml
  - 2-platform-network-Service.yaml
  - 3-pulsar.yaml
  - 3-pulsewatcher.yaml
  - 3-virtual.yaml
  - 4-ingress.yaml

images:
  - name: insolar/assured-ledger
    newName: ci:5000/assured-ledger
    newTag: latest